[app]
title = 批次计算器
package.name = batchcalculator
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0
requirements = python3,kivy
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.9.1
fullscreen = 0
android.presplash_color = white
android.permissions = INTERNET
android.api = 33
android.minapi = 21
android.sdk_build_tools = 30.0.3
android.ndk = 25b
android.archs = arm64-v8a, armeabi-v7a
android.accept_sdk_license = True
